apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "-text=Hello from {{ .Release.Namespace }}"